### ISSUE TITLE
Don't know why my figcaptions are different.

### ISSUE THREAD

**Issue by EmmaJLussier** [EmmaJLussier/dinosaur-designs#1]
@hellachella @raven-rhea

Hey so I think I got my markbot to work! I just recloned the folder to a different place in my computer. I was previously cloneing projects to my SSD card, so I put this project in my documents. I think it's good now, weird cause I did my other projects in therean they worked. Just thought you like to know incase someone else had my problem.

So I an stuck on the last bit my figcaptions are a lot bigger than the reference.
<img width="1635" alt="Screen Shot 2021-03-11 at 7 46 40 AM" src="https://user-images.githubusercontent.com/77282460/110789498-f16cfe00-823d-11eb-88e0-9bfe189a5eb4.png">

**Comment by EmmaJLussier** [comment]
Just looked back at the screenshot and I think my h2 are off as well

**Comment by raven-rhea** [comment]
It's because its the wrong font, In your html change the font family to font-family: Georgia, serif;

**Comment by EmmaJLussier** [comment]
Thank you Raven! theres just a problem with the size I'm not sure how to fix 
![Screen Shot 2021-03-11 at 3 12 01 PM](https://user-images.githubusercontent.com/77282460/110848601-46c80000-827c-11eb-9e92-36fbc2d8ed36.png)

**Comment by hellachella** [comment]
Remove the class of "intro" from the bottom two figcaptions in your HTML. It should only be applied to the first.

**Comment by EmmaJLussier** [comment]
Thank you :)
